---
- name: Install supervisor on centos
  yum: name=supervisor state=present
  when: ansible_os_family == 'RedHat'

- name: Install supervisor on debian
  apt: pkg=supervisor state=present force=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  
- name: Hack to repair supervisor for 3.10.8
  become: yes
  become_user: root
  command: pip install supervisor==4.2.2
